report_lines_starting_with_to_be_deleted:
  - Mobile
  - RegNo
  - CMH
  - correlation
  - Method
  - Dr
  - only
  - Report
  - Page
  - End
  - Sample
  - EDTASample
  - SerumSample
  - M.D
  - LABORATORY
  - Biochemistry
